### ISSUE TITLE
Move around missions.

### ISSUE THREAD

**Issue by genskaar** [genskaar/tb_geo#4]
LS missions are all in the correct zones but may require some slight moving around to match up with the actual mission positions in-game.

**Comment by celrick** [comment]
Phase 2:
https://www.youtube.com/watch?v=diKRFdNKvgM

**Comment by celrick** [comment]
Phase 1:
https://www.youtube.com/watch?v=Hzjt1ZE39eM

**Comment by celrick** [comment]
phase 3 https://www.youtube.com/watch?v=pr5SOxOIISA

**Comment by celrick** [comment]
phase 4:
https://us.v-cdn.net/6025736/uploads/editor/5f/9tde6yfofvp1.png

Need to find images of the other 2 territories for the position of nodes.
