### ISSUE TITLE
Update information on territory points

### ISSUE THREAD

**Issue by Sepifanovskiy** [genskaar/tb_geo#61]
Good evening!

I've noticed that map and game data doesn't match anymore

Could you, please fix it?

![map](https://user-images.githubusercontent.com/67445191/145837399-d8f0a821-ed20-4b8b-b690-4ac809faa70c.png)
?
![game](https://user-images.githubusercontent.com/67445191/145837496-c56b3e5f-4935-4f83-857c-68fe421ff35a.jpg)

**Comment by genskaar** [comment]
Hi :wave:
I think you may be looking at the wrong zone on the map? The one to the left matches the second of the screenshots you sent 
Cheers

**Comment by Sepifanovskiy** [comment]
I'll die  of shame ...
I'm extremely sorry, man ...

**Comment by genskaar** [comment]
It's no problem. Let me know if there are any other issues you find.
